# -*- coding: utf-8 -*-
"""hashtag_CD.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vM1C3TL-zP7G1pK9kqkiunUktIGxoozU
"""

pip install pandas

import pandas as pd

from google.colab import files
uploaded = files.upload()

base = pd.read_csv('titanic_train.csv')

base.head() #metodo

base.tail()  #metodo

base.shape

#coluna = 1
#linha = 0

base.shape[0]

display(base)

base.dtypes

base.info()

base.isnull().sum()

base.describe()

base['Survived']

from pandas.core.algorithms import value_counts
base.Survived,value_counts

base[["Survived",'Sex',"Age"]]

base.head()

base[base.Fare > 100]

base[(base.Parch > 1) | (base.SibSp > 1)]

base[(base.Parch > 1) & (base.SibSp > 1)].head()

base.loc[(base.Parch > 1) & (base.SibSp > 1)]

base.loc[(base.Parch > 1) | (base.SibSp > 1),["PassengerId","Parch","SibSp"]].head()

base.iloc[30:40,3:6]  #linhas

pip install matplotlib

import matplotlib.pyplot as plt

base.Fare.hist(bins=20);

base.Pclass.plot.bar();

base.Pclass.value_counts().plot.bar();

base['Fare'].plot.kde();